// Generated by scripts/build-public-site.mjs in the private project repository.
window.R78_CONFIG = {"mode":"apps-script","apiUrl":"https://script.google.com/macros/s/AKfycbw_PdbtfXB-48JVanvPnZ92GsSx9KBpxjcUO7S20HsPe681qp16GbQpi-ymlBx0z0Gy/exec"};
